# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 15:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinamicform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputmodel',
            name='input_name',
        ),
        migrations.AddField(
            model_name='inputmodel',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
            preserve_default=False,
        ),
    ]
