# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinamicform', '0002_auto_20181017_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputmodel',
            name='field',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
