# Generated by Django 4.0.2 on 2022-02-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinamicform', '0003_inputmodel_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
